//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::secrets::Entity as Secrets;
pub use super::secrets_history::Entity as SecretsHistory;
pub use super::secrets_origin_data::Entity as SecretsOriginData;
pub use super::vgroup::Entity as Vgroup;
