//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::preference::Entity as Preference;
pub use super::secrets::Entity as Secrets;
pub use super::secrets_recycle::Entity as SecretsRecycle;
pub use super::workspace::Entity as Workspace;
