[package]
name = "vault_core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aes-gcm.workspace = true
bip39.workspace = true
data-encoding.workspace = true
getrandom.workspace = true
hmac.workspace = true
keepass = { version = "0.13.18", features = ["_merge", "save_kdbx4"] }
percent-encoding.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
tempfile = "3"
url.workspace = true
uuid.workspace = true
zeroize.workspace = true
