// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_path_available`, `get_vault`, `insert_vault_session`, `into_entry`, `parse_uuid`, `path_identity`, `read_vault_sessions`, `with_vault_mut`, `write_vault_sessions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OtpSessions`, `SessionVaultMerger`, `VaultSessions`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `merge`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

/// Create and unlock a new KDBX workspace. Existing files are never overwritten.
Future<VaultHandle> createVault({
  required String path,
  required String name,
  required String masterPassword,
}) => RustLib.instance.api.crateApiSimpleCreateVault(
  path: path,
  name: name,
  masterPassword: masterPassword,
);

/// Unlock an existing KDBX workspace. Existing vault passwords have no length policy.
Future<VaultHandle> openVault({
  required String path,
  required String masterPassword,
}) => RustLib.instance.api.crateApiSimpleOpenVault(
  path: path,
  masterPassword: masterPassword,
);

void closeVault({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleCloseVault(handleId: handleId);

/// Drop all decrypted databases and zeroize all stored master passwords.
void lockAllVaults() => RustLib.instance.api.crateApiSimpleLockAllVaults();

List<VaultEntryView> listEntries({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleListEntries(handleId: handleId);

Future<String> createEntry({
  required BigInt handleId,
  required VaultEntryInput input,
}) => RustLib.instance.api.crateApiSimpleCreateEntry(
  handleId: handleId,
  input: input,
);

Future<void> updateEntry({
  required BigInt handleId,
  required String entryId,
  required VaultEntryInput input,
}) => RustLib.instance.api.crateApiSimpleUpdateEntry(
  handleId: handleId,
  entryId: entryId,
  input: input,
);

Future<void> deleteEntry({required BigInt handleId, required String entryId}) =>
    RustLib.instance.api.crateApiSimpleDeleteEntry(
      handleId: handleId,
      entryId: entryId,
    );

String revealEntryField({
  required BigInt handleId,
  required String entryId,
  required SensitiveField field,
}) => RustLib.instance.api.crateApiSimpleRevealEntryField(
  handleId: handleId,
  entryId: entryId,
  field: field,
);

OtpPreview currentEntryOtp({
  required BigInt handleId,
  required String entryId,
  required PlatformInt64 unixSeconds,
}) => RustLib.instance.api.crateApiSimpleCurrentEntryOtp(
  handleId: handleId,
  entryId: entryId,
  unixSeconds: unixSeconds,
);

Future<String> importOtpToVault({
  required BigInt handleId,
  required String uri,
  required PlatformInt64 modifiedAtUnixMs,
}) => RustLib.instance.api.crateApiSimpleImportOtpToVault(
  handleId: handleId,
  uri: uri,
  modifiedAtUnixMs: modifiedAtUnixMs,
);

/// Synchronize one unlocked vault using conditional WebDAV writes, encrypted
/// backups, KDBX merge, and post-upload verification.
Future<SyncResult> syncWebdav({
  required BigInt handleId,
  required String endpoint,
  required String username,
  required String password,
  required bool allowInsecureHttp,
  required String backupDirectory,
}) => RustLib.instance.api.crateApiSimpleSyncWebdav(
  handleId: handleId,
  endpoint: endpoint,
  username: username,
  password: password,
  allowInsecureHttp: allowInsecureHttp,
  backupDirectory: backupDirectory,
);

/// Legacy ephemeral OTP import retained for the locked-vault preview flow.
OtpHandle importOtpUri({required String uri}) =>
    RustLib.instance.api.crateApiSimpleImportOtpUri(uri: uri);

OtpPreview currentOtp({
  required BigInt handleId,
  required PlatformInt64 unixSeconds,
}) => RustLib.instance.api.crateApiSimpleCurrentOtp(
  handleId: handleId,
  unixSeconds: unixSeconds,
);

void removeOtp({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleRemoveOtp(handleId: handleId);

enum BridgeError {
  invalidInput,
  invalidOtp,
  otpNotFound,
  vaultNotFound,
  vaultAlreadyOpen,
  entryNotFound,
  fieldUnavailable,
  wrongPasswordOrInvalidVault,
  fileRead,
  fileWrite,
  sessionUnavailable,
  syncFailed,
}

class OtpHandle {
  final BigInt id;
  final String issuer;
  final String account;

  const OtpHandle({
    required this.id,
    required this.issuer,
    required this.account,
  });

  @override
  int get hashCode => id.hashCode ^ issuer.hashCode ^ account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpHandle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          issuer == other.issuer &&
          account == other.account;
}

class OtpPreview {
  final String code;
  final BigInt? validForSeconds;

  const OtpPreview({required this.code, this.validForSeconds});

  @override
  int get hashCode => code.hashCode ^ validForSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpPreview &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          validForSeconds == other.validForSeconds;
}

enum SensitiveField { password, notes }

class SyncResult {
  final int attempts;
  final bool merged;

  const SyncResult({required this.attempts, required this.merged});

  @override
  int get hashCode => attempts.hashCode ^ merged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          attempts == other.attempts &&
          merged == other.merged;
}

class VaultEntryInput {
  final VaultEntryKind kind;
  final String title;
  final String username;
  final String password;
  final String url;
  final String notes;
  final List<String> tags;
  final String? otpUri;

  /// Keep the existing protected OTP field during an update without exposing its seed.
  final bool preserveExistingOtp;
  final PlatformInt64 modifiedAtUnixMs;

  const VaultEntryInput({
    required this.kind,
    required this.title,
    required this.username,
    required this.password,
    required this.url,
    required this.notes,
    required this.tags,
    this.otpUri,
    required this.preserveExistingOtp,
    required this.modifiedAtUnixMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      otpUri.hashCode ^
      preserveExistingOtp.hashCode ^
      modifiedAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultEntryInput &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          tags == other.tags &&
          otpUri == other.otpUri &&
          preserveExistingOtp == other.preserveExistingOtp &&
          modifiedAtUnixMs == other.modifiedAtUnixMs;
}

enum VaultEntryKind { login, otp, recoveryCodes, secureNote }

class VaultEntryView {
  final String id;
  final VaultEntryKind kind;
  final String title;
  final String username;
  final String url;
  final bool hasPassword;
  final bool hasOtp;
  final List<String> tags;
  final PlatformInt64 modifiedAtUnixMs;

  const VaultEntryView({
    required this.id,
    required this.kind,
    required this.title,
    required this.username,
    required this.url,
    required this.hasPassword,
    required this.hasOtp,
    required this.tags,
    required this.modifiedAtUnixMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      username.hashCode ^
      url.hashCode ^
      hasPassword.hashCode ^
      hasOtp.hashCode ^
      tags.hashCode ^
      modifiedAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultEntryView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          title == other.title &&
          username == other.username &&
          url == other.url &&
          hasPassword == other.hasPassword &&
          hasOtp == other.hasOtp &&
          tags == other.tags &&
          modifiedAtUnixMs == other.modifiedAtUnixMs;
}

class VaultHandle {
  final BigInt id;

  const VaultHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}
