// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attachment_view`, `ensure_path_available`, `entry_view`, `get_vault`, `icon_view`, `insert_vault_session`, `into_entry`, `parse_uuid`, `path_identity`, `read_vault_sessions`, `with_vault_mut`, `write_vault_sessions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OtpSessions`, `SessionVaultMerger`, `VaultSessions`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `merge`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

/// Create and unlock a new KDBX workspace. Existing files are never overwritten.
Future<VaultHandle> createVault({
  required String path,
  required String name,
  required String masterPassword,
}) => RustLib.instance.api.crateApiSimpleCreateVault(
  path: path,
  name: name,
  masterPassword: masterPassword,
);

/// Unlock an existing KDBX workspace. Existing vault passwords have no length policy.
Future<VaultHandle> openVault({
  required String path,
  required String masterPassword,
}) => RustLib.instance.api.crateApiSimpleOpenVault(
  path: path,
  masterPassword: masterPassword,
);

/// Return a cryptographically random stable workspace identifier.
String generateWorkspaceId() =>
    RustLib.instance.api.crateApiSimpleGenerateWorkspaceId();

/// Validate and copy an external vault into app-owned storage before opening it.
Future<VaultHandle> importVault({
  required String sourcePath,
  required String destinationPath,
  required String name,
  required String masterPassword,
}) => RustLib.instance.api.crateApiSimpleImportVault(
  sourcePath: sourcePath,
  destinationPath: destinationPath,
  name: name,
  masterPassword: masterPassword,
);

Future<QuickUnlockEnrollment> prepareQuickUnlockEnrollment({
  required BigInt handleId,
  required String workspaceId,
  Uint8List? existingKeyring,
}) => RustLib.instance.api.crateApiSimplePrepareQuickUnlockEnrollment(
  handleId: handleId,
  workspaceId: workspaceId,
  existingKeyring: existingKeyring,
);

Future<Uint8List> removeQuickUnlockMaterial({
  required String workspaceId,
  required List<int> keyring,
}) => RustLib.instance.api.crateApiSimpleRemoveQuickUnlockMaterial(
  workspaceId: workspaceId,
  keyring: keyring,
);

/// Unlock multiple independent workspaces after one platform biometric prompt.
/// Individual failures are isolated and reported without exposing their cause.
Future<QuickUnlockBatchResult> openVaultsWithQuickUnlock({
  required List<QuickUnlockRequest> requests,
  required List<int> keyring,
}) => RustLib.instance.api.crateApiSimpleOpenVaultsWithQuickUnlock(
  requests: requests,
  keyring: keyring,
);

void closeVault({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleCloseVault(handleId: handleId);

/// Drop all decrypted databases and zeroize all stored master passwords.
void lockAllVaults() => RustLib.instance.api.crateApiSimpleLockAllVaults();

List<VaultEntryView> listEntries({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleListEntries(handleId: handleId);

VaultContentSnapshot vaultContent({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleVaultContent(handleId: handleId);

Future<String> createEntry({
  required BigInt handleId,
  required VaultEntryInput input,
}) => RustLib.instance.api.crateApiSimpleCreateEntry(
  handleId: handleId,
  input: input,
);

Future<String> createEntryInGroup({
  required BigInt handleId,
  required String groupId,
  required VaultEntryInput input,
}) => RustLib.instance.api.crateApiSimpleCreateEntryInGroup(
  handleId: handleId,
  groupId: groupId,
  input: input,
);

Future<String> createGroup({
  required BigInt handleId,
  required String parentId,
  required String name,
}) => RustLib.instance.api.crateApiSimpleCreateGroup(
  handleId: handleId,
  parentId: parentId,
  name: name,
);

Future<String> createGroupWithIcon({
  required BigInt handleId,
  required String parentId,
  required String name,
  int? builtInIconId,
}) => RustLib.instance.api.crateApiSimpleCreateGroupWithIcon(
  handleId: handleId,
  parentId: parentId,
  name: name,
  builtInIconId: builtInIconId,
);

Future<void> renameGroup({
  required BigInt handleId,
  required String groupId,
  required String name,
}) => RustLib.instance.api.crateApiSimpleRenameGroup(
  handleId: handleId,
  groupId: groupId,
  name: name,
);

Future<void> setGroupIcon({
  required BigInt handleId,
  required String groupId,
  int? builtInIconId,
}) => RustLib.instance.api.crateApiSimpleSetGroupIcon(
  handleId: handleId,
  groupId: groupId,
  builtInIconId: builtInIconId,
);

Uint8List loadCustomIcon({
  required BigInt handleId,
  required String customIconId,
}) => RustLib.instance.api.crateApiSimpleLoadCustomIcon(
  handleId: handleId,
  customIconId: customIconId,
);

Future<void> setEntryFavorite({
  required BigInt handleId,
  required String entryId,
  required bool favorite,
}) => RustLib.instance.api.crateApiSimpleSetEntryFavorite(
  handleId: handleId,
  entryId: entryId,
  favorite: favorite,
);

Future<void> addEntryAttachment({
  required BigInt handleId,
  required String entryId,
  required String attachmentName,
  required String sourcePath,
  required bool replace,
}) => RustLib.instance.api.crateApiSimpleAddEntryAttachment(
  handleId: handleId,
  entryId: entryId,
  attachmentName: attachmentName,
  sourcePath: sourcePath,
  replace: replace,
);

Future<void> exportEntryAttachment({
  required BigInt handleId,
  required String entryId,
  required String attachmentName,
  required String destinationPath,
  required bool overwrite,
}) => RustLib.instance.api.crateApiSimpleExportEntryAttachment(
  handleId: handleId,
  entryId: entryId,
  attachmentName: attachmentName,
  destinationPath: destinationPath,
  overwrite: overwrite,
);

Future<void> renameEntryAttachment({
  required BigInt handleId,
  required String entryId,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiSimpleRenameEntryAttachment(
  handleId: handleId,
  entryId: entryId,
  oldName: oldName,
  newName: newName,
);

Future<void> removeEntryAttachment({
  required BigInt handleId,
  required String entryId,
  required String attachmentName,
}) => RustLib.instance.api.crateApiSimpleRemoveEntryAttachment(
  handleId: handleId,
  entryId: entryId,
  attachmentName: attachmentName,
);

PasswordHealthView auditPasswordHealth({
  required BigInt handleId,
  int? staleAfterDays,
  required PlatformInt64 nowUnixMs,
}) => RustLib.instance.api.crateApiSimpleAuditPasswordHealth(
  handleId: handleId,
  staleAfterDays: staleAfterDays,
  nowUnixMs: nowUnixMs,
);

GeneratedPasswordView generateRandomPassword({
  required int length,
  required bool lowercase,
  required bool uppercase,
  required bool digits,
  required bool symbols,
  required String symbolCharacters,
  required bool excludeAmbiguous,
}) => RustLib.instance.api.crateApiSimpleGenerateRandomPassword(
  length: length,
  lowercase: lowercase,
  uppercase: uppercase,
  digits: digits,
  symbols: symbols,
  symbolCharacters: symbolCharacters,
  excludeAmbiguous: excludeAmbiguous,
);

String defaultPasswordSymbols() =>
    RustLib.instance.api.crateApiSimpleDefaultPasswordSymbols();

String normalizePasswordSymbols({required String value}) =>
    RustLib.instance.api.crateApiSimpleNormalizePasswordSymbols(value: value);

GeneratedPasswordView generatePassphrase({
  required int wordCount,
  required String separator,
  required bool capitalize,
  required bool includeNumber,
}) => RustLib.instance.api.crateApiSimpleGeneratePassphrase(
  wordCount: wordCount,
  separator: separator,
  capitalize: capitalize,
  includeNumber: includeNumber,
);

Future<void> moveGroup({
  required BigInt handleId,
  required String groupId,
  required String destinationId,
}) => RustLib.instance.api.crateApiSimpleMoveGroup(
  handleId: handleId,
  groupId: groupId,
  destinationId: destinationId,
);

Future<void> moveEntry({
  required BigInt handleId,
  required String entryId,
  required String destinationId,
}) => RustLib.instance.api.crateApiSimpleMoveEntry(
  handleId: handleId,
  entryId: entryId,
  destinationId: destinationId,
);

Future<String> enableRecycleBin({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleEnableRecycleBin(handleId: handleId);

Future<void> trashEntry({required BigInt handleId, required String entryId}) =>
    RustLib.instance.api.crateApiSimpleTrashEntry(
      handleId: handleId,
      entryId: entryId,
    );

Future<void> trashGroup({required BigInt handleId, required String groupId}) =>
    RustLib.instance.api.crateApiSimpleTrashGroup(
      handleId: handleId,
      groupId: groupId,
    );

Future<void> restoreEntry({
  required BigInt handleId,
  required String entryId,
}) => RustLib.instance.api.crateApiSimpleRestoreEntry(
  handleId: handleId,
  entryId: entryId,
);

Future<void> restoreGroup({
  required BigInt handleId,
  required String groupId,
}) => RustLib.instance.api.crateApiSimpleRestoreGroup(
  handleId: handleId,
  groupId: groupId,
);

Future<void> permanentlyDeleteGroup({
  required BigInt handleId,
  required String groupId,
}) => RustLib.instance.api.crateApiSimplePermanentlyDeleteGroup(
  handleId: handleId,
  groupId: groupId,
);

Future<void> emptyRecycleBin({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleEmptyRecycleBin(handleId: handleId);

Future<void> updateEntry({
  required BigInt handleId,
  required String entryId,
  required VaultEntryInput input,
}) => RustLib.instance.api.crateApiSimpleUpdateEntry(
  handleId: handleId,
  entryId: entryId,
  input: input,
);

Future<void> deleteEntry({required BigInt handleId, required String entryId}) =>
    RustLib.instance.api.crateApiSimpleDeleteEntry(
      handleId: handleId,
      entryId: entryId,
    );

String revealEntryField({
  required BigInt handleId,
  required String entryId,
  required SensitiveField field,
}) => RustLib.instance.api.crateApiSimpleRevealEntryField(
  handleId: handleId,
  entryId: entryId,
  field: field,
);

OtpPreview currentEntryOtp({
  required BigInt handleId,
  required String entryId,
  required PlatformInt64 unixSeconds,
}) => RustLib.instance.api.crateApiSimpleCurrentEntryOtp(
  handleId: handleId,
  entryId: entryId,
  unixSeconds: unixSeconds,
);

Future<String> importOtpToVault({
  required BigInt handleId,
  required String uri,
  required PlatformInt64 modifiedAtUnixMs,
}) => RustLib.instance.api.crateApiSimpleImportOtpToVault(
  handleId: handleId,
  uri: uri,
  modifiedAtUnixMs: modifiedAtUnixMs,
);

/// Synchronize one unlocked vault using conditional WebDAV writes, encrypted
/// backups, KDBX merge, and post-upload verification.
Future<SyncResult> syncWebdav({
  required BigInt handleId,
  required String endpoint,
  required String username,
  required String password,
  required bool allowInsecureHttp,
  required String backupDirectory,
}) => RustLib.instance.api.crateApiSimpleSyncWebdav(
  handleId: handleId,
  endpoint: endpoint,
  username: username,
  password: password,
  allowInsecureHttp: allowInsecureHttp,
  backupDirectory: backupDirectory,
);

/// Legacy ephemeral OTP import retained for the locked-vault preview flow.
OtpHandle importOtpUri({required String uri}) =>
    RustLib.instance.api.crateApiSimpleImportOtpUri(uri: uri);

OtpPreview currentOtp({
  required BigInt handleId,
  required PlatformInt64 unixSeconds,
}) => RustLib.instance.api.crateApiSimpleCurrentOtp(
  handleId: handleId,
  unixSeconds: unixSeconds,
);

void removeOtp({required BigInt handleId}) =>
    RustLib.instance.api.crateApiSimpleRemoveOtp(handleId: handleId);

enum BridgeError {
  invalidInput,
  invalidOtp,
  otpNotFound,
  vaultNotFound,
  vaultAlreadyOpen,
  entryNotFound,
  groupNotFound,
  recycleBinDisabled,
  protectedVaultObject,
  invalidVaultMove,
  invalidVaultIcon,
  attachmentNotFound,
  invalidAttachment,
  attachmentLimitExceeded,
  invalidGeneratorRequest,
  fieldUnavailable,
  wrongPasswordOrInvalidVault,
  fileRead,
  fileWrite,
  sessionUnavailable,
  syncFailed,
  quickUnlockFailed,
}

class GeneratedPasswordView {
  final String value;
  final int entropyBits;

  const GeneratedPasswordView({required this.value, required this.entropyBits});

  @override
  int get hashCode => value.hashCode ^ entropyBits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratedPasswordView &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          entropyBits == other.entropyBits;
}

class HealthFindingView {
  final String entryId;
  final List<HealthRiskView> risks;

  const HealthFindingView({required this.entryId, required this.risks});

  @override
  int get hashCode => entryId.hashCode ^ risks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthFindingView &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          risks == other.risks;
}

enum HealthRiskView { empty, duplicate, weak, stale, missingOtp }

class OtpHandle {
  final BigInt id;
  final String issuer;
  final String account;

  const OtpHandle({
    required this.id,
    required this.issuer,
    required this.account,
  });

  @override
  int get hashCode => id.hashCode ^ issuer.hashCode ^ account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpHandle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          issuer == other.issuer &&
          account == other.account;
}

class OtpPreview {
  final String code;
  final BigInt? validForSeconds;
  final BigInt? periodSeconds;

  const OtpPreview({
    required this.code,
    this.validForSeconds,
    this.periodSeconds,
  });

  @override
  int get hashCode =>
      code.hashCode ^ validForSeconds.hashCode ^ periodSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpPreview &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          validForSeconds == other.validForSeconds &&
          periodSeconds == other.periodSeconds;
}

class PasswordHealthView {
  final List<HealthFindingView> findings;

  const PasswordHealthView({required this.findings});

  @override
  int get hashCode => findings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordHealthView &&
          runtimeType == other.runtimeType &&
          findings == other.findings;
}

class QuickUnlockBatchResult {
  final List<QuickUnlockOpened> opened;
  final List<String> failedWorkspaceIds;

  const QuickUnlockBatchResult({
    required this.opened,
    required this.failedWorkspaceIds,
  });

  @override
  int get hashCode => opened.hashCode ^ failedWorkspaceIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickUnlockBatchResult &&
          runtimeType == other.runtimeType &&
          opened == other.opened &&
          failedWorkspaceIds == other.failedWorkspaceIds;
}

class QuickUnlockEnrollment {
  final Uint8List envelope;
  final Uint8List updatedKeyring;

  const QuickUnlockEnrollment({
    required this.envelope,
    required this.updatedKeyring,
  });

  @override
  int get hashCode => envelope.hashCode ^ updatedKeyring.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickUnlockEnrollment &&
          runtimeType == other.runtimeType &&
          envelope == other.envelope &&
          updatedKeyring == other.updatedKeyring;
}

class QuickUnlockOpened {
  final String workspaceId;
  final BigInt handleId;

  const QuickUnlockOpened({required this.workspaceId, required this.handleId});

  @override
  int get hashCode => workspaceId.hashCode ^ handleId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickUnlockOpened &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          handleId == other.handleId;
}

class QuickUnlockRequest {
  final String workspaceId;
  final String path;
  final Uint8List envelope;

  const QuickUnlockRequest({
    required this.workspaceId,
    required this.path,
    required this.envelope,
  });

  @override
  int get hashCode => workspaceId.hashCode ^ path.hashCode ^ envelope.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickUnlockRequest &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          path == other.path &&
          envelope == other.envelope;
}

enum SensitiveField { password, notes }

class SyncResult {
  final int attempts;
  final bool merged;

  const SyncResult({required this.attempts, required this.merged});

  @override
  int get hashCode => attempts.hashCode ^ merged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          attempts == other.attempts &&
          merged == other.merged;
}

class VaultAttachmentView {
  final String name;
  final BigInt size;
  final bool isProtected;

  const VaultAttachmentView({
    required this.name,
    required this.size,
    required this.isProtected,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ isProtected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultAttachmentView &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          isProtected == other.isProtected;
}

class VaultContentSnapshot {
  final String rootGroupId;
  final bool recycleBinEnabled;
  final String? recycleBinId;
  final List<VaultGroupView> groups;
  final List<VaultEntryView> entries;

  const VaultContentSnapshot({
    required this.rootGroupId,
    required this.recycleBinEnabled,
    this.recycleBinId,
    required this.groups,
    required this.entries,
  });

  @override
  int get hashCode =>
      rootGroupId.hashCode ^
      recycleBinEnabled.hashCode ^
      recycleBinId.hashCode ^
      groups.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultContentSnapshot &&
          runtimeType == other.runtimeType &&
          rootGroupId == other.rootGroupId &&
          recycleBinEnabled == other.recycleBinEnabled &&
          recycleBinId == other.recycleBinId &&
          groups == other.groups &&
          entries == other.entries;
}

class VaultEntryInput {
  final VaultEntryKind kind;
  final String title;
  final String username;
  final String password;
  final String url;
  final String notes;
  final List<String> tags;
  final String? otpUri;

  /// Keep the existing protected OTP field during an update without exposing its seed.
  final bool preserveExistingOtp;
  final PlatformInt64 modifiedAtUnixMs;

  const VaultEntryInput({
    required this.kind,
    required this.title,
    required this.username,
    required this.password,
    required this.url,
    required this.notes,
    required this.tags,
    this.otpUri,
    required this.preserveExistingOtp,
    required this.modifiedAtUnixMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      otpUri.hashCode ^
      preserveExistingOtp.hashCode ^
      modifiedAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultEntryInput &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          tags == other.tags &&
          otpUri == other.otpUri &&
          preserveExistingOtp == other.preserveExistingOtp &&
          modifiedAtUnixMs == other.modifiedAtUnixMs;
}

enum VaultEntryKind { login, otp, recoveryCodes, secureNote }

class VaultEntryView {
  final String id;
  final VaultEntryKind kind;
  final String title;
  final String username;
  final String url;
  final bool hasPassword;
  final bool hasOtp;
  final List<String> tags;
  final PlatformInt64 modifiedAtUnixMs;
  final String groupId;
  final bool isInRecycleBin;
  final VaultIconView icon;
  final List<VaultAttachmentView> attachments;
  final bool isFavorite;

  const VaultEntryView({
    required this.id,
    required this.kind,
    required this.title,
    required this.username,
    required this.url,
    required this.hasPassword,
    required this.hasOtp,
    required this.tags,
    required this.modifiedAtUnixMs,
    required this.groupId,
    required this.isInRecycleBin,
    required this.icon,
    required this.attachments,
    required this.isFavorite,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      username.hashCode ^
      url.hashCode ^
      hasPassword.hashCode ^
      hasOtp.hashCode ^
      tags.hashCode ^
      modifiedAtUnixMs.hashCode ^
      groupId.hashCode ^
      isInRecycleBin.hashCode ^
      icon.hashCode ^
      attachments.hashCode ^
      isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultEntryView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          title == other.title &&
          username == other.username &&
          url == other.url &&
          hasPassword == other.hasPassword &&
          hasOtp == other.hasOtp &&
          tags == other.tags &&
          modifiedAtUnixMs == other.modifiedAtUnixMs &&
          groupId == other.groupId &&
          isInRecycleBin == other.isInRecycleBin &&
          icon == other.icon &&
          attachments == other.attachments &&
          isFavorite == other.isFavorite;
}

class VaultGroupView {
  final String id;
  final String? parentId;
  final String name;
  final bool isRoot;
  final bool isRecycleBin;
  final VaultIconView icon;

  const VaultGroupView({
    required this.id,
    this.parentId,
    required this.name,
    required this.isRoot,
    required this.isRecycleBin,
    required this.icon,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      parentId.hashCode ^
      name.hashCode ^
      isRoot.hashCode ^
      isRecycleBin.hashCode ^
      icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultGroupView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parentId == other.parentId &&
          name == other.name &&
          isRoot == other.isRoot &&
          isRecycleBin == other.isRecycleBin &&
          icon == other.icon;
}

class VaultHandle {
  final BigInt id;

  const VaultHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

enum VaultIconKind { none, builtIn, custom }

class VaultIconView {
  final VaultIconKind kind;
  final int? builtInId;
  final String? customId;

  const VaultIconView({required this.kind, this.builtInId, this.customId});

  @override
  int get hashCode => kind.hashCode ^ builtInId.hashCode ^ customId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultIconView &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          builtInId == other.builtInId &&
          customId == other.customId;
}
