// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VaultEntryInput dco_decode_box_autoadd_vault_entry_input(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  GeneratedPasswordView dco_decode_generated_password_view(dynamic raw);

  @protected
  HealthFindingView dco_decode_health_finding_view(dynamic raw);

  @protected
  HealthRiskView dco_decode_health_risk_view(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<HealthFindingView> dco_decode_list_health_finding_view(dynamic raw);

  @protected
  List<HealthRiskView> dco_decode_list_health_risk_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QuickUnlockOpened> dco_decode_list_quick_unlock_opened(dynamic raw);

  @protected
  List<QuickUnlockRequest> dco_decode_list_quick_unlock_request(dynamic raw);

  @protected
  List<VaultAttachmentView> dco_decode_list_vault_attachment_view(dynamic raw);

  @protected
  List<VaultEntryView> dco_decode_list_vault_entry_view(dynamic raw);

  @protected
  List<VaultGroupView> dco_decode_list_vault_group_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OtpHandle dco_decode_otp_handle(dynamic raw);

  @protected
  OtpPreview dco_decode_otp_preview(dynamic raw);

  @protected
  PasswordHealthView dco_decode_password_health_view(dynamic raw);

  @protected
  QuickUnlockBatchResult dco_decode_quick_unlock_batch_result(dynamic raw);

  @protected
  QuickUnlockEnrollment dco_decode_quick_unlock_enrollment(dynamic raw);

  @protected
  QuickUnlockOpened dco_decode_quick_unlock_opened(dynamic raw);

  @protected
  QuickUnlockRequest dco_decode_quick_unlock_request(dynamic raw);

  @protected
  SensitiveField dco_decode_sensitive_field(dynamic raw);

  @protected
  SyncResult dco_decode_sync_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultAttachmentView dco_decode_vault_attachment_view(dynamic raw);

  @protected
  VaultContentSnapshot dco_decode_vault_content_snapshot(dynamic raw);

  @protected
  VaultEntryInput dco_decode_vault_entry_input(dynamic raw);

  @protected
  VaultEntryKind dco_decode_vault_entry_kind(dynamic raw);

  @protected
  VaultEntryView dco_decode_vault_entry_view(dynamic raw);

  @protected
  VaultGroupView dco_decode_vault_group_view(dynamic raw);

  @protected
  VaultHandle dco_decode_vault_handle(dynamic raw);

  @protected
  VaultIconKind dco_decode_vault_icon_kind(dynamic raw);

  @protected
  VaultIconView dco_decode_vault_icon_view(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VaultEntryInput sse_decode_box_autoadd_vault_entry_input(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  GeneratedPasswordView sse_decode_generated_password_view(
    SseDeserializer deserializer,
  );

  @protected
  HealthFindingView sse_decode_health_finding_view(
    SseDeserializer deserializer,
  );

  @protected
  HealthRiskView sse_decode_health_risk_view(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<HealthFindingView> sse_decode_list_health_finding_view(
    SseDeserializer deserializer,
  );

  @protected
  List<HealthRiskView> sse_decode_list_health_risk_view(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QuickUnlockOpened> sse_decode_list_quick_unlock_opened(
    SseDeserializer deserializer,
  );

  @protected
  List<QuickUnlockRequest> sse_decode_list_quick_unlock_request(
    SseDeserializer deserializer,
  );

  @protected
  List<VaultAttachmentView> sse_decode_list_vault_attachment_view(
    SseDeserializer deserializer,
  );

  @protected
  List<VaultEntryView> sse_decode_list_vault_entry_view(
    SseDeserializer deserializer,
  );

  @protected
  List<VaultGroupView> sse_decode_list_vault_group_view(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OtpHandle sse_decode_otp_handle(SseDeserializer deserializer);

  @protected
  OtpPreview sse_decode_otp_preview(SseDeserializer deserializer);

  @protected
  PasswordHealthView sse_decode_password_health_view(
    SseDeserializer deserializer,
  );

  @protected
  QuickUnlockBatchResult sse_decode_quick_unlock_batch_result(
    SseDeserializer deserializer,
  );

  @protected
  QuickUnlockEnrollment sse_decode_quick_unlock_enrollment(
    SseDeserializer deserializer,
  );

  @protected
  QuickUnlockOpened sse_decode_quick_unlock_opened(
    SseDeserializer deserializer,
  );

  @protected
  QuickUnlockRequest sse_decode_quick_unlock_request(
    SseDeserializer deserializer,
  );

  @protected
  SensitiveField sse_decode_sensitive_field(SseDeserializer deserializer);

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultAttachmentView sse_decode_vault_attachment_view(
    SseDeserializer deserializer,
  );

  @protected
  VaultContentSnapshot sse_decode_vault_content_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  VaultEntryInput sse_decode_vault_entry_input(SseDeserializer deserializer);

  @protected
  VaultEntryKind sse_decode_vault_entry_kind(SseDeserializer deserializer);

  @protected
  VaultEntryView sse_decode_vault_entry_view(SseDeserializer deserializer);

  @protected
  VaultGroupView sse_decode_vault_group_view(SseDeserializer deserializer);

  @protected
  VaultHandle sse_decode_vault_handle(SseDeserializer deserializer);

  @protected
  VaultIconKind sse_decode_vault_icon_kind(SseDeserializer deserializer);

  @protected
  VaultIconView sse_decode_vault_icon_view(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vault_entry_input(
    VaultEntryInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_generated_password_view(
    GeneratedPasswordView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_health_finding_view(
    HealthFindingView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_health_risk_view(
    HealthRiskView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_health_finding_view(
    List<HealthFindingView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_health_risk_view(
    List<HealthRiskView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_quick_unlock_opened(
    List<QuickUnlockOpened> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_quick_unlock_request(
    List<QuickUnlockRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_attachment_view(
    List<VaultAttachmentView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_entry_view(
    List<VaultEntryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_group_view(
    List<VaultGroupView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_otp_handle(OtpHandle self, SseSerializer serializer);

  @protected
  void sse_encode_otp_preview(OtpPreview self, SseSerializer serializer);

  @protected
  void sse_encode_password_health_view(
    PasswordHealthView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quick_unlock_batch_result(
    QuickUnlockBatchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quick_unlock_enrollment(
    QuickUnlockEnrollment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quick_unlock_opened(
    QuickUnlockOpened self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quick_unlock_request(
    QuickUnlockRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sensitive_field(
    SensitiveField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_attachment_view(
    VaultAttachmentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_content_snapshot(
    VaultContentSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_entry_input(
    VaultEntryInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_entry_kind(
    VaultEntryKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_entry_view(
    VaultEntryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_group_view(
    VaultGroupView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_handle(VaultHandle self, SseSerializer serializer);

  @protected
  void sse_encode_vault_icon_kind(VaultIconKind self, SseSerializer serializer);

  @protected
  void sse_encode_vault_icon_view(VaultIconView self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
