// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -231058654;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_authenticator_vault',
        ioDirectory: '../../crates/native_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiSimpleCloseVault({required BigInt handleId});

  Future<String> crateApiSimpleCreateEntry({
    required BigInt handleId,
    required VaultEntryInput input,
  });

  Future<VaultHandle> crateApiSimpleCreateVault({
    required String path,
    required String name,
    required String masterPassword,
  });

  OtpPreview crateApiSimpleCurrentEntryOtp({
    required BigInt handleId,
    required String entryId,
    required PlatformInt64 unixSeconds,
  });

  OtpPreview crateApiSimpleCurrentOtp({
    required BigInt handleId,
    required PlatformInt64 unixSeconds,
  });

  Future<void> crateApiSimpleDeleteEntry({
    required BigInt handleId,
    required String entryId,
  });

  Future<String> crateApiSimpleImportOtpToVault({
    required BigInt handleId,
    required String uri,
    required PlatformInt64 modifiedAtUnixMs,
  });

  OtpHandle crateApiSimpleImportOtpUri({required String uri});

  Future<void> crateApiSimpleInitApp();

  List<VaultEntryView> crateApiSimpleListEntries({required BigInt handleId});

  void crateApiSimpleLockAllVaults();

  Future<VaultHandle> crateApiSimpleOpenVault({
    required String path,
    required String masterPassword,
  });

  void crateApiSimpleRemoveOtp({required BigInt handleId});

  String crateApiSimpleRevealEntryField({
    required BigInt handleId,
    required String entryId,
    required SensitiveField field,
  });

  Future<SyncResult> crateApiSimpleSyncWebdav({
    required BigInt handleId,
    required String endpoint,
    required String username,
    required String password,
    required bool allowInsecureHttp,
    required String backupDirectory,
  });

  Future<void> crateApiSimpleUpdateEntry({
    required BigInt handleId,
    required String entryId,
    required VaultEntryInput input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiSimpleCloseVault({required BigInt handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleCloseVaultConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCloseVaultConstMeta =>
      const TaskConstMeta(debugName: "close_vault", argNames: ["handleId"]);

  @override
  Future<String> crateApiSimpleCreateEntry({
    required BigInt handleId,
    required VaultEntryInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_box_autoadd_vault_entry_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleCreateEntryConstMeta,
        argValues: [handleId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateEntryConstMeta => const TaskConstMeta(
    debugName: "create_entry",
    argNames: ["handleId", "input"],
  );

  @override
  Future<VaultHandle> crateApiSimpleCreateVault({
    required String path,
    required String name,
    required String masterPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(masterPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_handle,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleCreateVaultConstMeta,
        argValues: [path, name, masterPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateVaultConstMeta => const TaskConstMeta(
    debugName: "create_vault",
    argNames: ["path", "name", "masterPassword"],
  );

  @override
  OtpPreview crateApiSimpleCurrentEntryOtp({
    required BigInt handleId,
    required String entryId,
    required PlatformInt64 unixSeconds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(entryId, serializer);
          sse_encode_i_64(unixSeconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_otp_preview,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleCurrentEntryOtpConstMeta,
        argValues: [handleId, entryId, unixSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCurrentEntryOtpConstMeta =>
      const TaskConstMeta(
        debugName: "current_entry_otp",
        argNames: ["handleId", "entryId", "unixSeconds"],
      );

  @override
  OtpPreview crateApiSimpleCurrentOtp({
    required BigInt handleId,
    required PlatformInt64 unixSeconds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_i_64(unixSeconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_otp_preview,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleCurrentOtpConstMeta,
        argValues: [handleId, unixSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCurrentOtpConstMeta => const TaskConstMeta(
    debugName: "current_otp",
    argNames: ["handleId", "unixSeconds"],
  );

  @override
  Future<void> crateApiSimpleDeleteEntry({
    required BigInt handleId,
    required String entryId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(entryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleDeleteEntryConstMeta,
        argValues: [handleId, entryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteEntryConstMeta => const TaskConstMeta(
    debugName: "delete_entry",
    argNames: ["handleId", "entryId"],
  );

  @override
  Future<String> crateApiSimpleImportOtpToVault({
    required BigInt handleId,
    required String uri,
    required PlatformInt64 modifiedAtUnixMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(uri, serializer);
          sse_encode_i_64(modifiedAtUnixMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleImportOtpToVaultConstMeta,
        argValues: [handleId, uri, modifiedAtUnixMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportOtpToVaultConstMeta =>
      const TaskConstMeta(
        debugName: "import_otp_to_vault",
        argNames: ["handleId", "uri", "modifiedAtUnixMs"],
      );

  @override
  OtpHandle crateApiSimpleImportOtpUri({required String uri}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_otp_handle,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleImportOtpUriConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportOtpUriConstMeta =>
      const TaskConstMeta(debugName: "import_otp_uri", argNames: ["uri"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<VaultEntryView> crateApiSimpleListEntries({required BigInt handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_vault_entry_view,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleListEntriesConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListEntriesConstMeta =>
      const TaskConstMeta(debugName: "list_entries", argNames: ["handleId"]);

  @override
  void crateApiSimpleLockAllVaults() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleLockAllVaultsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLockAllVaultsConstMeta =>
      const TaskConstMeta(debugName: "lock_all_vaults", argNames: []);

  @override
  Future<VaultHandle> crateApiSimpleOpenVault({
    required String path,
    required String masterPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(masterPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_handle,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleOpenVaultConstMeta,
        argValues: [path, masterPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleOpenVaultConstMeta => const TaskConstMeta(
    debugName: "open_vault",
    argNames: ["path", "masterPassword"],
  );

  @override
  void crateApiSimpleRemoveOtp({required BigInt handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleRemoveOtpConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRemoveOtpConstMeta =>
      const TaskConstMeta(debugName: "remove_otp", argNames: ["handleId"]);

  @override
  String crateApiSimpleRevealEntryField({
    required BigInt handleId,
    required String entryId,
    required SensitiveField field,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(entryId, serializer);
          sse_encode_sensitive_field(field, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleRevealEntryFieldConstMeta,
        argValues: [handleId, entryId, field],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRevealEntryFieldConstMeta =>
      const TaskConstMeta(
        debugName: "reveal_entry_field",
        argNames: ["handleId", "entryId", "field"],
      );

  @override
  Future<SyncResult> crateApiSimpleSyncWebdav({
    required BigInt handleId,
    required String endpoint,
    required String username,
    required String password,
    required bool allowInsecureHttp,
    required String backupDirectory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(endpoint, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_bool(allowInsecureHttp, serializer);
          sse_encode_String(backupDirectory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_result,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleSyncWebdavConstMeta,
        argValues: [
          handleId,
          endpoint,
          username,
          password,
          allowInsecureHttp,
          backupDirectory,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSyncWebdavConstMeta => const TaskConstMeta(
    debugName: "sync_webdav",
    argNames: [
      "handleId",
      "endpoint",
      "username",
      "password",
      "allowInsecureHttp",
      "backupDirectory",
    ],
  );

  @override
  Future<void> crateApiSimpleUpdateEntry({
    required BigInt handleId,
    required String entryId,
    required VaultEntryInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(entryId, serializer);
          sse_encode_box_autoadd_vault_entry_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSimpleUpdateEntryConstMeta,
        argValues: [handleId, entryId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateEntryConstMeta => const TaskConstMeta(
    debugName: "update_entry",
    argNames: ["handleId", "entryId", "input"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  VaultEntryInput dco_decode_box_autoadd_vault_entry_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vault_entry_input(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeError.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VaultEntryView> dco_decode_list_vault_entry_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vault_entry_view).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  OtpHandle dco_decode_otp_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OtpHandle(
      id: dco_decode_u_64(arr[0]),
      issuer: dco_decode_String(arr[1]),
      account: dco_decode_String(arr[2]),
    );
  }

  @protected
  OtpPreview dco_decode_otp_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OtpPreview(
      code: dco_decode_String(arr[0]),
      validForSeconds: dco_decode_opt_box_autoadd_u_64(arr[1]),
    );
  }

  @protected
  SensitiveField dco_decode_sensitive_field(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SensitiveField.values[raw as int];
  }

  @protected
  SyncResult dco_decode_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SyncResult(
      attempts: dco_decode_u_32(arr[0]),
      merged: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultEntryInput dco_decode_vault_entry_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return VaultEntryInput(
      kind: dco_decode_vault_entry_kind(arr[0]),
      title: dco_decode_String(arr[1]),
      username: dco_decode_String(arr[2]),
      password: dco_decode_String(arr[3]),
      url: dco_decode_String(arr[4]),
      notes: dco_decode_String(arr[5]),
      tags: dco_decode_list_String(arr[6]),
      otpUri: dco_decode_opt_String(arr[7]),
      preserveExistingOtp: dco_decode_bool(arr[8]),
      modifiedAtUnixMs: dco_decode_i_64(arr[9]),
    );
  }

  @protected
  VaultEntryKind dco_decode_vault_entry_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultEntryKind.values[raw as int];
  }

  @protected
  VaultEntryView dco_decode_vault_entry_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return VaultEntryView(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_vault_entry_kind(arr[1]),
      title: dco_decode_String(arr[2]),
      username: dco_decode_String(arr[3]),
      url: dco_decode_String(arr[4]),
      hasPassword: dco_decode_bool(arr[5]),
      hasOtp: dco_decode_bool(arr[6]),
      tags: dco_decode_list_String(arr[7]),
      modifiedAtUnixMs: dco_decode_i_64(arr[8]),
    );
  }

  @protected
  VaultHandle dco_decode_vault_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return VaultHandle(id: dco_decode_u_64(arr[0]));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  VaultEntryInput sse_decode_box_autoadd_vault_entry_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vault_entry_input(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeError.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VaultEntryView> sse_decode_list_vault_entry_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VaultEntryView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vault_entry_view(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OtpHandle sse_decode_otp_handle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_issuer = sse_decode_String(deserializer);
    var var_account = sse_decode_String(deserializer);
    return OtpHandle(id: var_id, issuer: var_issuer, account: var_account);
  }

  @protected
  OtpPreview sse_decode_otp_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_validForSeconds = sse_decode_opt_box_autoadd_u_64(deserializer);
    return OtpPreview(code: var_code, validForSeconds: var_validForSeconds);
  }

  @protected
  SensitiveField sse_decode_sensitive_field(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SensitiveField.values[inner];
  }

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_attempts = sse_decode_u_32(deserializer);
    var var_merged = sse_decode_bool(deserializer);
    return SyncResult(attempts: var_attempts, merged: var_merged);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultEntryInput sse_decode_vault_entry_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_vault_entry_kind(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_otpUri = sse_decode_opt_String(deserializer);
    var var_preserveExistingOtp = sse_decode_bool(deserializer);
    var var_modifiedAtUnixMs = sse_decode_i_64(deserializer);
    return VaultEntryInput(
      kind: var_kind,
      title: var_title,
      username: var_username,
      password: var_password,
      url: var_url,
      notes: var_notes,
      tags: var_tags,
      otpUri: var_otpUri,
      preserveExistingOtp: var_preserveExistingOtp,
      modifiedAtUnixMs: var_modifiedAtUnixMs,
    );
  }

  @protected
  VaultEntryKind sse_decode_vault_entry_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VaultEntryKind.values[inner];
  }

  @protected
  VaultEntryView sse_decode_vault_entry_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_vault_entry_kind(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_hasPassword = sse_decode_bool(deserializer);
    var var_hasOtp = sse_decode_bool(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_modifiedAtUnixMs = sse_decode_i_64(deserializer);
    return VaultEntryView(
      id: var_id,
      kind: var_kind,
      title: var_title,
      username: var_username,
      url: var_url,
      hasPassword: var_hasPassword,
      hasOtp: var_hasOtp,
      tags: var_tags,
      modifiedAtUnixMs: var_modifiedAtUnixMs,
    );
  }

  @protected
  VaultHandle sse_decode_vault_handle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    return VaultHandle(id: var_id);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vault_entry_input(
    VaultEntryInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_entry_input(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_vault_entry_view(
    List<VaultEntryView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vault_entry_view(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_otp_handle(OtpHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.issuer, serializer);
    sse_encode_String(self.account, serializer);
  }

  @protected
  void sse_encode_otp_preview(OtpPreview self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_opt_box_autoadd_u_64(self.validForSeconds, serializer);
  }

  @protected
  void sse_encode_sensitive_field(
    SensitiveField self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.attempts, serializer);
    sse_encode_bool(self.merged, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_entry_input(
    VaultEntryInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_entry_kind(self.kind, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.otpUri, serializer);
    sse_encode_bool(self.preserveExistingOtp, serializer);
    sse_encode_i_64(self.modifiedAtUnixMs, serializer);
  }

  @protected
  void sse_encode_vault_entry_kind(
    VaultEntryKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_vault_entry_view(
    VaultEntryView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_vault_entry_kind(self.kind, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_bool(self.hasPassword, serializer);
    sse_encode_bool(self.hasOtp, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_i_64(self.modifiedAtUnixMs, serializer);
  }

  @protected
  void sse_encode_vault_handle(VaultHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
  }
}
