// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void init({required String dataPath}) =>
    RustLib.instance.api.crateApiApiInit(dataPath: dataPath);

String appinfo({required String name}) =>
    RustLib.instance.api.crateApiApiAppinfo(name: name);
